charts/kestra/templates/autoscaler.yaml

autoscaling v2beta2 is marked as deprecated since kubernetes v1.23

fix(helm) autoscaler api version depends on cluster version

---

charts/kestra/values.yaml

Otherwise it is never pulled again.

feat: set pull policy to always as we use by default latest-full

---

charts/kestra/templates/_helpers.tpl
charts/kestra/values.yaml

Added ability to use pre created configmaps or secrets for Kestra env variables for external secret controllers like sealed-secrets operator
---
Tried rendering the chart locally via
```
helm template kestra . --output-dir=./tmp
```
---

feat: ability to mount pre created configmaps and secrets via envFrom

---

charts/kestra/templates/_helpers.tpl

Fix the indentation issue for adding prefixes in pre existing configmaps and secrets to Kestra pod enviroment variables
---
1. enabled extraSecretEnvFrom and extraConfigMapEnvFrom in values.yaml
2. templated locally via
```bash
helm template kestra . --output-dir=./tmp
```
3. Tested against k8s api

Fix: indention issue for prefixes in envFrom block

---

charts/kestra/templates/service.yaml
charts/kestra/values.yaml

Hi !
I'd like to add `loadBalancerIP` to service spec to allow use cases such as Internal Load Balancers on Google Kubernetes Engine with static internal IP reserved in advance.  
It helps with:
- Increasing security by not exposing the service with an external IP.
- Allowing more advanced automation in provisioning infrastructure.
See [this](https://cloud.google.com/kubernetes-engine/docs/concepts/service-load-balancer#load_balancer_types), [this](https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing#enabling_internal_load_balancer_subsetting_in_a_new_cluster) and [this](https://cloud.google.com/kubernetes-engine/docs/concepts/service-load-balancer-parameters).
---
Tested on GKE v1.27.8-gke.1067004 STABLE Release Channel with the Kestra chart deployed with …

feat(helm): add loadBalancerIP to service spec

---

charts/kestra/templates/_helpers.tpl
charts/kestra/values.yaml

Add a possibility to load kestra configuration from an existing secret. This allow to hide some part of the kestra configuration in a secret not managed by the helm chart.

feat(helm): Add loading configuration from external secret

---

charts/kestra/templates/_helpers.tpl
charts/kestra/values.yaml

This PR allow user to set labels and annotations per deployment (eg webserver, worker, etc..)
```
webserver:
...
labels:
mybeautifullabel: "OK"
annotations:
myannotation: "Hello"
worker:
...
labels:
mybeautifullabel: "OK"
annotations:
myannotation: "Hello"
```

feat: Allow to add deployment annotations and labels

---

charts/kestra/templates/_helpers.tpl
charts/kestra/values.yaml

The `httpGet` probe instructions allows the configuration of custom headers. However, it doesn't support secret access. Hence configuring a secret base64 header to probe secured endpoints is unsupported. The header would be visible in the pod definition as base64.
This changes enables the use of `exec` instruction on the probes which do have access to environment variables of the deployment container.
* Introduces the ability to opt-out the `httpGet` instructions on all probes. 
* Support for `exec` configuration on the probes.
---
The changes can be observed using the following helm command with the following values:
```sh
helm template kestra . -s templates/deployment.yaml --values temp-values.yaml
```
```yaml
startupProbe:
httpGetEnabled: false
exec:
command:
- bash
- -c
- 'curl --fail …
```

feat(helm): add support for custom exec command on deployment probes

---

charts/kestra/templates/NOTES.txt

When installing the kestra helm chart in a non-default namespace, the current instructions generated by the helm chart are missing the namespace, which leads to not finding the pod for port-forwarding.
---
Install the helm chart in a non-default namespace
```
helm install kestra kestra/kestra --namespace=other
```
The instructions should properly show:
```
kubectl port-forward --namespace other $POD_NAME 8080:8080
```

Include helm release namespace in port-forwarding instructions

---

charts/kestra/templates/_helpers.tpl

This PR adds the user-defined deployment labels to the pod template. This ensures that the labels defined in the deployment configuration are also applied to the pods.
- #### Values.yaml:
```
deployments:
webserver:
enabled: true
replicaCount: 1
labels:
my-label: "my-value"
```
- #### Deployment labels:
```
Labels:
app.kubernetes.io/component=indexer
app.kubernetes.io/instance=kestra
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=kestra
app.kubernetes.io/version=0.19.0
helm.sh/chart=kestra-0.19.0
my-label=my-value
```
- #### Webserver pod labels:
```
Labels:
app.kubernetes.io/component=indexer
app.kubernetes.io/instance=kestra
app.kubernetes.io/name=kestra
pod-template-hash=595cbc6d75
my-label=my-value
```
This improvement builds upon my previous [PR …

feat: Add user-defined deployment labels to deployment's pod template

---

charts/kestra/Chart.yaml

- In `charts/kestra/Chart.yaml` new `version` is 0.20.7
- In `charts/kestra/Chart.yaml` new `appVersion` is v0.20.7
[1]: https://github.com/kestra-io/helm-charts/actions/runs/12376198680

Helm chart update from 0.20.6 to 0.20.7

---

charts/kestra/Chart.yaml

- In `charts/kestra/Chart.yaml` new `version` is 0.21.0
- In `charts/kestra/Chart.yaml` new `appVersion` is v0.21.0
[1]: https://github.com/kestra-io/helm-charts/actions/runs/13136426006

Helm chart update from 0.20.13 to 0.21.0

---

charts/kestra/Chart.yaml

- In `charts/kestra/Chart.yaml` new `version` is 0.21.3
- In `charts/kestra/Chart.yaml` new `appVersion` is v0.21.3
[1]: https://github.com/kestra-io/helm-charts/actions/runs/13399480889

Helm chart update from 0.21.2 to 0.21.3

---

charts/kestra/values.yaml

We recently experienced unintended Kestra pod restarts in our Kubernetes cluster. After analysis we discovered that this was due to a misconfigured liveness probe in the Helm chart. The probe was pointing to `/health`, which depends on external components of the pod. This caused the pod to be restarted by Kubernetes when an external component was unavailable.
To resolve this, we updated the value file to configure the liveness and readiness probes to use the correct Micronaut health paths:
- **Liveness probe** now points to `/health/liveness`
- **Readiness probe** now points to `/health/readiness`
This ensures that the probes accurately reflect the health of the java application itself.
---
This will resolve issue https://github.com/kestra-io/helm-charts/issues/20

fix: Use micronaut healthcheck path for liveness and readiness probes

---

charts/kestra/Chart.yaml

- In `charts/kestra/Chart.yaml` new `version` is 0.21.6
- In `charts/kestra/Chart.yaml` new `appVersion` is v0.21.6
[1]: https://github.com/kestra-io/helm-charts/actions/runs/13794477188

Helm chart update from 0.21.5 to 0.21.6

---

charts/kestra/Chart.yaml

- In `charts/kestra/Chart.yaml` new `version` is 0.21.7
- In `charts/kestra/Chart.yaml` new `appVersion` is v0.21.7
[1]: https://github.com/kestra-io/helm-charts/actions/runs/13929012614

Helm chart update from 0.21.6 to 0.21.7

---

charts/kestra/Chart.yaml

- In `charts/kestra/Chart.yaml` new `version` is 0.21.8
- In `charts/kestra/Chart.yaml` new `appVersion` is v0.21.8
[1]: https://github.com/kestra-io/helm-charts/actions/runs/14058059504

Helm chart update from 0.21.7 to 0.21.8

---

charts/kestra/Chart.yaml

- In `charts/kestra/Chart.yaml` new `version` is 0.21.9
- In `charts/kestra/Chart.yaml` new `appVersion` is v0.21.9
[1]: https://github.com/kestra-io/helm-charts/actions/runs/14090120147

Helm chart update from 0.21.8 to 0.21.9

---

charts/kestra/Chart.yaml

- In `charts/kestra/Chart.yaml` new `version` is 0.22.2
- In `charts/kestra/Chart.yaml` new `appVersion` is v0.22.2
[1]: https://github.com/kestra-io/helm-charts/actions/runs/14336155382

Helm chart update from 0.22.1 to 0.22.2

---

charts/kestra/values.yaml

The goal is have extraPorts capabilities, like extraVolumes, extraContainers, etc. The data in extraPorts follow the way you add a port in kubernetes into a deployment.

chore(): add extraPorts

---

charts/kestra/Chart.yaml

- In `charts/kestra/Chart.yaml` new `version` is 0.22.5
- In `charts/kestra/Chart.yaml` new `appVersion` is v0.22.5
[1]: https://github.com/kestra-io/helm-charts/actions/runs/14736307502

Helm chart update from 0.22.4 to 0.22.9

---

charts/kestra/Chart.yaml

- In `charts/kestra/Chart.yaml` new `version` is 0.23.0
- In `charts/kestra/Chart.yaml` new `appVersion` is v0.23.0
[1]: https://github.com/kestra-io/helm-charts/actions/runs/15704118675

Helm chart update from 0.22.13 to 0.23.0

---

charts/kestra/Chart.yaml

- In `charts/kestra/Chart.yaml` new `version` is 0.23.5
- In `charts/kestra/Chart.yaml` new `appVersion` is v0.23.5
[1]: https://github.com/kestra-io/helm-charts/actions/runs/16145417097

Helm chart update from 0.23.1 to 0.23.5

---

charts/kestra/Chart.yaml

- In `charts/kestra/Chart.yaml` new `version` is 0.24.0
- In `charts/kestra/Chart.yaml` new `appVersion` is v0.24.0
[1]: https://github.com/kestra-io/helm-charts/actions/runs/16750221973

Helm chart update from 0.23.9 to 0.24.0
